#!/dis/sh.dis

for i in $* {
	basename = `{echo $i |sed '/[\[\]]+/d'}	
}

blname = `{echo $basename |tr '_' ' '}
fname =`{echo $basename |tr 'A-Z␣ -' a-z___}

if {echo $fname |grep '[0-9]+_[0-9]+_[0-9]+'}{
	target=$notedir/daily/$fname.note
}{
	target=$notedir/$fname.note
}

if {! ftest -f $target}{
	echo '#+title: '$1$nl$nl >>$target
}

backlinks $blname
plumb $target
