#!/dis/sh.dis

for i in $* {
	fname =`{echo $i |tr 'A-Z ' a-z-}
}

if {echo $fname |grep '[0-9]+-[0-9]+-[0-9]+'}{
	target=$notedir/daily/$fname.note
}{
	target=$notedir/$fname.note
}

if {! ftest -f $target}{
	echo '#+title: '$1$nl$nl >>$target
}

plumb $target
