#!/dis/sh.dis

today=`{os date -I}
moment=`{os date +%T}

if {! ftest -f $todofile}{
	echo '#+title: Todo'$nl$nl >>$todofile
}

for i in $* {
	echo 'TODO '$i'	['$today $moment'] [finishdate]'$nl >>$todofile
}
